In [1]:
with open('genes_2510.txt', 'r') as file:
    # Read the contents of the file into a list using readlines()
    genes_2510 = list(map(lambda x: x[:-1], file.readlines()))
print(len(genes_2510))
print(genes_2510[:5])

2510
['UBB', 'UBC', 'UBA52', 'RPS27A', 'UBA1']

In [2]:
import pandas as pd

drug_response_df = pd.read_csv("../0208/cell_drug_auc_final_1111.csv")
print(drug_response_df.shape)
drug_response_df.head()

(692, 386)

,ARXSPAN_ID,JW-7-24-1,KIN001-260,NSC-87877,GNE-317,NAVITOCLAX,PLX-4720,ERK5-IN-1,VX-11E,TGX-221,...,BIX02189,ISPINESIB MESYLATE,KIN001-135,KIN001-206,KIN001-236,KIN001-266,LUMINESPIB,NUTLIN-3A,SGC0946,SL 0101-1
0,ACH-000001,0.778432,0.951321,0.840287,-99999.000000,-99999.000000,0.936410,0.891908,0.402122,0.659600,...,0.982272,0.733492,0.072277,0.983536,-99999.000000,0.651746,0.982084,0.893777,0.983861,0.933035
1,ACH-000002,0.788327,0.874760,0.760137,0.905754,0.930764,0.991068,0.278288,0.972905,0.558774,...,0.899628,0.604228,0.046061,0.918265,0.865628,-99999.000000,0.985921,0.839175,0.988639,0.533204
2,ACH-000004,0.737630,0.938733,0.835441,0.808964,0.966133,0.983552,-99999.000000,0.993912,0.596027,...,0.965245,0.782295,0.366912,0.844979,0.761323,-99999.000000,0.980945,0.946694,0.992605,0.761956
3,ACH-000006,0.176396,0.571569,0.581729,0.585938,0.958510,0.935574,0.600428,-99999.000000,0.596056,...,0.834158,0.605360,0.124930,0.813384,0.782187,-99999.000000,0.971058,0.871277,-99999.000000,0.495020
4,ACH-000007,0.569751,0.755449,0.954924,0.939587,0.965638,0.932666,-99999.000000,0.956481,0.838692,...,0.927519,0.812955,0.719780,0.815099,0.795736,0.860768,0.983317,0.888067,0.987564,0.787948

In [3]:
import numpy as np

# define column names
columns = list(genes_2510)

# define row index names
index_names = drug_response_df.ARXSPAN_ID.values

# create empty dataframe with column names, and row index
data = np.zeros((len(index_names), len(columns))) # initialize all value to be 0
cnv_df = pd.DataFrame(data, columns=columns, index=index_names)
cnv_df.shape

(692, 2510)

In [4]:
### CNV data
CCLE_cnv = pd.read_csv('../0208/CCLE_gene_cn.csv', low_memory=False, index_col=0)
CCLE_cnv.head()

,DDX11L1 (84771),WASH7P (653635),MIR6859-1 (102466751),MIR1302-2 (100302278),FAM138A (645520),OR4F5 (79501),WASH9P (102723897),MIR6859-2 (102465909),OR4F29 (729759),AL669831.3 (101928626),...,TTTY17B (474151),TTTY4B (474149),BPY2B (442867),DAZ3 (57054),DAZ4 (57135),BPY2C (442868),TTTY4C (474150),CSPG4P1Y (114758),CDY1 (9085),TTTY3 (114760)
ACH-000267,1.149159,1.149159,1.149159,1.149159,1.149159,1.149159,1.149159,1.149159,1.149159,1.149159,...,5.421627e-01,5.421627e-01,5.421627e-01,5.421627e-01,5.421627e-01,5.421627e-01,5.421627e-01,5.421627e-01,5.421627e-01,5.421627e-01
ACH-001408,1.039446,1.039446,1.039446,1.039446,1.039446,1.039446,1.039446,1.039446,1.039446,1.039446,...,5.107920e-01,5.107920e-01,5.107920e-01,5.107920e-01,5.107920e-01,5.107920e-01,5.107920e-01,5.107920e-01,5.107920e-01,5.107920e-01
ACH-000617,0.762353,0.762353,0.762353,0.762353,0.762353,0.762353,0.762353,0.762353,0.762353,0.762353,...,1.032871e-08,1.032871e-08,1.032871e-08,1.032871e-08,1.032871e-08,1.032871e-08,1.032871e-08,1.032871e-08,1.032871e-08,1.032871e-08
ACH-002123,1.137564,1.137564,1.137564,1.137564,1.137564,1.137564,1.137564,1.137564,1.137564,1.137564,...,4.717688e-01,4.717688e-01,4.717688e-01,4.717688e-01,4.717688e-01,4.717688e-01,4.717688e-01,4.717688e-01,4.717688e-01,4.717688e-01
ACH-000519,1.005822,1.005822,1.005822,1.005822,1.005822,1.005822,1.005822,1.005822,1.005822,1.005822,...,8.638107e-10,8.638107e-10,8.638107e-10,8.638107e-10,8.638107e-10,8.638107e-10,8.638107e-10,8.638107e-10,8.638107e-10,8.638107e-10

In [5]:
CCLE_genes = list(map(lambda x:x.split(" ")[0], CCLE_cnv.columns))
CCLE_genes[:10]

['DDX11L1',
 'WASH7P',
 'MIR6859-1',
 'MIR1302-2',
 'FAM138A',
 'OR4F5',
 'WASH9P',
 'MIR6859-2',
 'OR4F29',
 'AL669831.3']

In [6]:
missing_gene_lst = []
for gene in cnv_df.columns.values:
    if gene not in list(CCLE_genes):
        missing_gene_lst.append(gene)
print(len(missing_gene_lst))
missing_gene_lst

13

['MICOS10-NBL1',
 'BUB1B-PAK6',
 'H3F3A',
 'MRE11A',
 'TERC',
 'FAM123B',
 'FAM46C',
 'C17orf39',
 'MLL',
 'MLL2',
 'MYCL1',
 'WHSC1',
 'WHSC1L1']

In [7]:
### synonym dictionary (map to Hugo Symbol used in CCLE)
gene_hugo_symbol_dict = {
    'COP1': "COP1, CFAP78, FAP78, RFWD2, RNF200",
    'ELOC': "ELOC, SIII, TCEB1",
    'ELOB': "ELOB, SIII, TCEB2",
    'MICOS10-NBL1': "MICOS10-NBL1, C1orf151-NBL1, DAN, DAND1, MINOS1-NBL1, NBL1",
    'HJV': "HJV, HFE2, HFE2A, JH, RGMC",
    'VEGFD': "VEGFD, FIGF, VEGF-D",
    'MAP3K20': "MAP3K20, AZK, CNM6, MLK7, MLT, MLTK, MLTKalpha, MLTKbeta, MRK, SFMMP, ZAK, mlklak, pk",
    'MAP3K14': "MAP3K14, FTDCR1B, HS, HSNIK, NIK",
    'CASTOR1': "CASTOR1, GATSL3",
    'CASTOR2': "CASTOR2, GATSL1, GATSL2",
    'PAK5': "PAK5, PAK7",
    'BUB1B-PAK6': "BUB1B-PAK6, PAK-5, PAK-6, PAK5, PAK6",
    'TMSB4Y': "TMSB4Y, TB4Y",
    'VSIR': "VSIR, B7-H5, B7H5, C10orf54, DD1alpha, Dies1, GI24, PD-1H, PP2135, SISP1, VISTA",
    'CD8B2': "CD8B2, CD8BP",
    'NECTIN2': "NECTIN2, CD112, HVEB, PRR2, PVRL2, PVRR2",
    'NECTIN3': "NECTIN3, CD113, CDW113, NECTIN-3, PPR3, PRR3, PVRL3, PVRR3",
    'CLDN34': "CLDN34",
    'PECAM1': "PECAM1, CD31, CD31/EndoCAM, GPIIA', PECA1, PECAM-1, endoCAM",
    'NECTIN1': "NECTIN1, CD111, CLPED1, ED4, HIgR, HV1S, HVEC, OFC7, PRR, PRR1, PVRL1, PVRR, PVRR1, SK-12, nectin-1",
    'CXCL8': "CXCL8, GCP-1, GCP1, IL8, LECT, LUCT, LYNAP, MDNCF, MONAP, NAF, NAP-1, NAP1, SCYB8",
    'CCL3L3': "CCL3L3, 464.2, D17S1718, G0S19-2, LD78, LD78BETA, SCYA3L, SCYA3L1",
    'GRK2': "GRK2, ADRBK1, BARK1, BETA-ARK1",
    'GRK3': "GRK3, ADRBK2, BARK2",
    'SEPTIN4': "SEPTIN4, ARTS, BRADEION, C17orf47, CE5B3, H5, MART, PNUTL2, SEP4, SEPT4, hCDCREL-2, hucep-7",
    'PIDD1': "PIDD1, LRDD, MRT75, PIDD",
    'TPTEP2-CSNK1E': "TPTEP2-CSNK1E, LOC400927-CSNK1E",
    'TLE7': "TLE7, chico",
    'CCN4': "CCN4, WISP1, WISP1-OT1, WISP1-UT1, WISP1c, WISP1i, WISP1tc",
    'ADGRB1': "ADGRB1, BAI1, GDAIF",
    'AFDN': "AFDN, AF6, MLL-AF6, MLLT4",
    'PLAAT3': "PLAAT3, AdPLA, H-REV107, H-REV107-1, HRASLS3, HREV107, HREV107-1, HREV107-3, HRSL3, PLA2G16, PLAAT-3",
    'GPHB5': "GPHB5, B5, GPB5, ZLUT1",
    'MOSMO': "MOSMO, ATTHOG, BC030336, C16orf52",
    'NECTIN4': "NECTIN4, EDSS1, LNIR, PRR4, PVRL4, nectin-4",
    'CD24': "ABCB1, ABC20, CD243, CLCS, GP170, MDR1, P-GP, PGY1, p-170",
    'MRE11': "MRE11, ATLD, HNGS1, MRE11A, MRE11B",
    'ABRAXAS1': "ABRAXAS1, ABRA1, CCDC98, FAM175A",
    'BABAM2': "BABAM2, BRCC4, BRCC45, BRE",
    'SEM1': "SEM1, C7orf76, DSS1, ECD, PSMD15, SHFD1, SHFM1, SHSF1, Shfdg1",
    'EMSY': "EMSY, C11orf30, GL002",
    'TERC': "TERC, DKCA1, PFBMFT2, SCARNA19, TER, TR, TRC3, hTR",
    'FAM123B': "AMER1, FAM123B, OSCS, WTX",
    'C17orf39': "GID4, C17orf39, VID2, VID24",
    'MLL': "MLLT1, ENL, LTG19, YEATS1",
    'MLL2': "KMT2B, CXXC10, DYT28, HRX2, MLL1B, MLL2, MLL4, MRD68, TRX2, WBP-7, WBP7",
    'MYCL1': "MYCL, L-Myc, LMYC, MYCL1, bHLHe38",
    "H3F3A": "H3-3A, BRYLIB1, H3-3B, H3.3A, H3F3, H3F3A",
    "MRE11A": "MRE11, ATLD, HNGS1, MRE11A, MRE11B",
    "FAM46C": "TENT5C, FAM46C",
    "WHSC1": "NSD2, KMT3F, KMT3G, MMSET, RAUST, REIIBP, TRX5, WHS, WHSC1",
    "WHSC1L1": "NSD3, KMT3F, KMT3G, WHISTLE, WHSC1L1, pp14328"
}

In [8]:
symbol_mapping_dict = {}
not_found_gene_lst = []
for gene in missing_gene_lst:
    if gene not in gene_hugo_symbol_dict:
        print(gene)
        continue
    lst = gene_hugo_symbol_dict[gene]
    found = False
    for symbol in list(lst.split(", ")):
        if symbol in CCLE_genes:
            if gene not in symbol_mapping_dict:
                symbol_mapping_dict[gene] = []
            symbol_mapping_dict[gene].append(symbol)
            found = True
    if not found:
        not_found_gene_lst.append(gene)
        print(gene, "Not Found")
print(len(not_found_gene_lst))

TERC Not Found
1

In [9]:
### multiple match
# BUB1B-PAK6 ['PAK5', 'PAK6'] -> PAK6
# H3F3A ['H3-3A', 'H3-3B'] -> H3-3A

for gene, lst in symbol_mapping_dict.items():
    if len(lst) > 1:
        print(gene, lst)

BUB1B-PAK6 ['PAK5', 'PAK6']
H3F3A ['H3-3A', 'H3-3B']

In [10]:
symbol_mapping_dict_final = {}
for gene, lst in symbol_mapping_dict.items():
    if len(lst) > 1:
        if gene == "BUB1B-PAK6":
            symbol_mapping_dict_final[gene] = "PAK6"
        if gene == "H3F3A":
            symbol_mapping_dict_final[gene] = "H3-3A"
    else:
        symbol_mapping_dict_final[gene] = lst[0]

In [11]:
columns = list(genes_2510)

# define row index names
index_names = drug_response_df.ARXSPAN_ID.values

# create empty dataframe with column names, and row index
data = np.zeros((len(index_names), len(columns))) # initialize all value to be 0
cnv_df = pd.DataFrame(data, columns=columns, index=index_names)
cnv_df.shape

(692, 2510)

In [12]:
CCLE_cnv.columns = list(map(lambda x:x.split(" ")[0], CCLE_cnv.columns))
CCLE_cnv.head()

,DDX11L1,WASH7P,MIR6859-1,MIR1302-2,FAM138A,OR4F5,WASH9P,MIR6859-2,OR4F29,AL669831.3,...,TTTY17B,TTTY4B,BPY2B,DAZ3,DAZ4,BPY2C,TTTY4C,CSPG4P1Y,CDY1,TTTY3
ACH-000267,1.149159,1.149159,1.149159,1.149159,1.149159,1.149159,1.149159,1.149159,1.149159,1.149159,...,5.421627e-01,5.421627e-01,5.421627e-01,5.421627e-01,5.421627e-01,5.421627e-01,5.421627e-01,5.421627e-01,5.421627e-01,5.421627e-01
ACH-001408,1.039446,1.039446,1.039446,1.039446,1.039446,1.039446,1.039446,1.039446,1.039446,1.039446,...,5.107920e-01,5.107920e-01,5.107920e-01,5.107920e-01,5.107920e-01,5.107920e-01,5.107920e-01,5.107920e-01,5.107920e-01,5.107920e-01
ACH-000617,0.762353,0.762353,0.762353,0.762353,0.762353,0.762353,0.762353,0.762353,0.762353,0.762353,...,1.032871e-08,1.032871e-08,1.032871e-08,1.032871e-08,1.032871e-08,1.032871e-08,1.032871e-08,1.032871e-08,1.032871e-08,1.032871e-08
ACH-002123,1.137564,1.137564,1.137564,1.137564,1.137564,1.137564,1.137564,1.137564,1.137564,1.137564,...,4.717688e-01,4.717688e-01,4.717688e-01,4.717688e-01,4.717688e-01,4.717688e-01,4.717688e-01,4.717688e-01,4.717688e-01,4.717688e-01
ACH-000519,1.005822,1.005822,1.005822,1.005822,1.005822,1.005822,1.005822,1.005822,1.005822,1.005822,...,8.638107e-10,8.638107e-10,8.638107e-10,8.638107e-10,8.638107e-10,8.638107e-10,8.638107e-10,8.638107e-10,8.638107e-10,8.638107e-10

In [13]:
count = 0
for i in cnv_df.index.values:
    count += 1
    for gene in cnv_df.columns.values:
        if gene in CCLE_genes:
            cnv_df.loc[i, gene] = CCLE_cnv.loc[i,gene]
        elif gene in symbol_mapping_dict_final:
            if symbol_mapping_dict_final[gene] in CCLE_genes:
                cnv_df.loc[i, gene] = CCLE_cnv.loc[i,symbol_mapping_dict_final[gene]]
    if count % 10 == 0:
        print(count)

10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
500
510
520
530
540
550
560
570
580
590
600
610
620
630
640
650
660
670
680
690

In [14]:
for i in cnv_df.columns:
    if cnv_df[i].sum() == 0:
        print(i)

TERC

In [15]:
cnv_df.to_csv("CCLE_cnv_2510.csv")

In [16]:
cnv_df_check = pd.read_csv("CCLE_cnv_2510.csv", index_col=0)
cnv_df_check.head()

,UBB,UBC,UBA52,RPS27A,UBA1,SAE1,UBA2,UBA3,UBA7,UBA6,...,GATA6,C17orf39,INPP4B,KLHL6,MLL,MLL2,MYCL1,WHSC1,WHSC1L1,PRKN
ACH-000001,1.117512,0.974899,0.683473,0.959903,0.713244,0.674357,1.481259,0.991710,0.964180,1.082980,...,0.707764,1.140180,1.065979,1.279539,0.685484,1.481259,0.912771,1.108171,1.156995,0.700798
ACH-000002,0.633720,0.999717,1.028104,1.003822,0.548741,1.028104,1.028104,1.011177,1.011177,1.006573,...,1.330282,0.633720,1.006573,1.011177,1.028104,1.028104,1.011689,1.006573,0.937941,1.095331
ACH-000004,0.814237,1.095285,1.095561,1.076712,0.428422,1.092396,1.054106,0.806563,1.107325,0.869114,...,1.046031,0.814237,0.828751,1.087986,1.031568,1.054106,1.332747,1.079673,1.279533,1.100919
ACH-000006,0.675625,0.674150,1.057955,1.002133,0.544724,1.057955,1.057955,1.017117,1.017117,1.014187,...,1.017746,0.675625,1.014187,1.017117,1.057955,1.057955,0.947284,1.014187,1.023474,1.216220
ACH-000007,0.970098,0.963609,0.954248,0.962907,0.552104,0.954248,0.954248,0.949038,0.964463,0.952543,...,0.958031,0.970098,0.952543,0.968089,0.954248,0.954248,0.971692,0.952543,0.957015,0.961695